### PR TITLE
Initial SPI Hub commit

### PR DESCRIPTION
**Pull request by fooforever**
Add SPI Hub extension board

### CODE REVIEW

**Comment by arthurwolf** [comment]
Really nice ! Thanks a lot !

**Comment by arthurwolf** [comment]
I believe this is functionally correct, however do you think there is some way you could make it more compact/aligned ? Also, I do not see any holes for attaching, am I missing something ?

**Comment by bobc** [comment]
Just a small FYI from me, the drill file doesn't match the gerbers? Possibly one was plotted with aux origin, the other not maybe.

**Comment by fooforever** [comment]
I'm new to KiCad so I've possibly messed up on the export somehow. I'll take a look at shrinking it a bit, I was just trying to stick to the grid recommendations for the mounting holes.

**Comment by arthurwolf** [comment]
Thanks !

**Comment by fooforever** [comment]
@arthurwolf Should I prioritise the size or the fitting to the grid for the mounting holes ? There's not quite enough room for everything on a 20x20

**Comment by arthurwolf** [comment]
@fooforever I think you should prioritize fitting to the grid, but if it's really having too high an impact on size, please note that fitting to a 10x10 grid is acceptable.

**Pull request merged**
